### ISSUE TITLE
Feedback for “How to use DNS.SB”

### ISSUE THREAD

**Issue by carvalho45** [dns-sb/dns.sb#21]
Hello,
I'm a new user of DNS.sb after opendns is not more available in France. My question is: Is it possible to enhance the protection in Internet by restricting some sites (pornography, malwares etc.) using DNS.sb? It seems we don't have an account and hence a dashboard to allow us to enhance the protection.
Yours sincerely,
Stéphane Carvalho

**Comment by Showfom** [comment]
Hello Stéphane,

We do not block any domains. You can use 3rd tools like adguard to block them.
