### ISSUE TITLE
DNS.SB not resolving 

### ISSUE THREAD

**Issue by thepunixxer** [dns-sb/dns.sb#22]
Hello, I'm from Philippines.

Why DNS.SB is not resolving ? It shows google and cloudflare

**Comment by Showfom** [comment]
Do you have any logs or screens?

**Comment by thepunixxer** [comment]
> Do you have any logs or screens?

![Screenshot_2024-07-08-19-24-39-001_com kiwibrowser browser](https://github.com/dns-sb/dns.sb/assets/146539863/d4837e85-4c0a-4c14-b322-ff7eb1cfdc18)

**Comment by sergeevabc** [comment]
Do you offer an alternative port for plain (un-encrypted) DNS in case ISP intercepts connections on port 53? For example, AdGuard DNS offers `94.140.14.14:5353`.

**Comment by Showfom** [comment]
No, we don't.
