### ISSUE TITLE
Add blocklist of famous quad9 dns 

### ISSUE THREAD

**Issue by trimechee** [dns-sb/dns.sb#25]
Hi, it will be great to add blocklist of famous secure Quad9 dns to more security feeling safe please, or add other blocklists of famous secure dns that block malwares virus like blocklist of cira dns, dns0, nextdns, thank you :

https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txt

**Comment by SukkaW** [comment]
It seems that the list mentioned is not maintained by the official quad9/IBM staff. Is the list trustworthy?

**Comment by SukkaW** [comment]
Also, Quad9 has lost against Sony Music and has to stop resolving specific domains: https://www.quad9.net/news/blog/quad9-and-sony-music-german-injunction-update-for-february-2023//

Does that blocklist also contain those domains (now and in the future)?

**Comment by SukkaW** [comment]
Duplicated #24, please move the discussion there instead.
