### ISSUE TITLE
just a technical question

### ISSUE THREAD

**Issue by masterofobzene** [dns-sb/dns.sb#7]
Hi guys! I've been wondering if I can directly configure DoT DNS servers on my router instead of using yogadns. Is it the same thing?
My router doesn't have DoT special settings like other modern routers do, but configuring the DoT DNS's  into the normal DNS address seems to work... in fact dns.sb web tells me that my requests are being encrypted.

Is it safe to use it like that? or yogadns does something extra?

thanks!

**Comment by Showfom** [comment]
You can set DoH or DoT on your OS, also using YogaDNS is another good choice.
